# Used vim to grab this:
rivers = c("Aalbach",
  "Abens",
  "Abens",
  "Abens",
  "Ach",
  "Ach",
  "Aisch",
  "Aisch",
  "Aisch",
  "Aisch",
  "Aisch",
  "Aiterach",
  "Aitnach",
  "Almbach",
  "Almosbach",
  "Altbach",
  "Altmühl",
  "Altmühl",
  "Altmühl",
  "Altmühl",
  "Altmühl",
  "Altmühl",
  "Altmühlüberleiter",
  "Alz",
  "Alz",
  "Alz",
  "Alz",
  "Alzkanal",
  "Alzkanal",
  "Ammer",
  "Ammer",
  "Ammer",
  "Amper",
  "Amper",
  "Amper",
  "Amper",
  "Amper",
  "Amper",
  "Amper",
  "Anlauter",
  "Antersdorfer Bach",
  "Arzbach",
  "Ascha",
  "Aschaff",
  "Attel",
  "Attel",
  "Aubach",
  "Auerbach",
  "Aurach",
  "Aurach",
  "Baunach",
  "Baunach",
  "Bayerische Schwarzach",
  "Bayerische Schwarzach",
  "Berchtesgadener Ache",
  "Bernauer Ache",
  "Beurerbach",
  "Bibert",
  "Bibert",
  "Billbach",
  "Bina",
  "Bischofswieser Ache",
  "Brautlach",
  "Breitach",
  "Breitbach",
  "Brend",
  "Brend",
  "Brenz",
  "Brombachsee",
  "Buchbach",
  "Castellbach",
  "Chamb",
  "Chamb",
  "Chamb",
  "Chamb",
  "Chamb",
  "Chamb",
  "Creußen",
  "Danglesbach",
  "Donau",
  "Donau",
  "Donau",
  "Donau",
  "Donau",
  "Donau",
  "Donau",
  "Donau",
  "Donau",
  "Donau",
  "Donau",
  "Donau",
  "Donau",
  "Donau",
  "Donau",
  "Donau",
  "Donau",
  "Donaumoos Ach",
  "Donaumoos Ach",
  "Durach",
  "Ecknach",
  "Egau",
  "Eger",
  "Eger",
  "Eger",
  "Ehenbach",
  "Eisbach",
  "Ellbach",
  "Els",
  "Elsava",
  "Elsava",
  "Erf",
  "Erlau",
  "Euzenauer Bach",
  "Eybach",
  "Felchbach",
  "Fensterbach",
  "Fichtelnaab",
  "Fichtenohe",
  "Flossach",
  "Frankenohe",
  "Freybach",
  "Fränkische Rezat",
  "Fränkische Rezat",
  "Fränkische Rezat",
  "Fränkische Rezat",
  "Fränkische Saale",
  "Fränkische Saale",
  "Fränkische Saale",
  "Fränkische Saale",
  "Förmitz",
  "Förmitz",
  "Füssener Achen",
  "Gailach",
  "Gaißa",
  "Gambach",
  "Geisbach",
  "Geltnach",
  "Gennach",
  "Georgenbach",
  "Gfällach",
  "Glonn",
  "Glonn",
  "Glonn",
  "Glonn",
  "Glonn",
  "Goldach",
  "Gollach",
  "Große Gaißach",
  "Große Laber",
  "Große Laber",
  "Große Ohe",
  "Große Ohe",
  "Große Vils",
  "Großer Regen",
  "Gröbenbach",
  "Gründlach",
  "Gunzesrieder Ach",
  "Götzinger Achen",
  "Günz",
  "Günz",
  "Günz",
  "Hafenlohr",
  "Haidenaab",
  "Haidenaab",
  "Haidenaab",
  "Halbammer",
  "Halblech",
  "Hammerbach",
  "Hammerbach",
  "Haselbach",
  "Haslach",
  "Haßlach",
  "Hengersberger Ohe",
  "Hennenbach",
  "Högenbach",
  "Höllbach",
  "Höllenbach",
  "Illach",
  "Iller",
  "Iller",
  "Iller",
  "Iller",
  "Iller",
  "Iller",
  "Illerkanal",
  "Ilm",
  "Ilm",
  "Ilm",
  "Ilz",
  "Ilz",
  "Inn",
  "Inn",
  "Inn",
  "Inn",
  "Inn",
  "Inn",
  "Inn",
  "Inn",
  "Inn",
  "Isar",
  "Isar",
  "Isar",
  "Isar",
  "Isar",
  "Isar",
  "Isar",
  "Isar",
  "Isar",
  "Isar",
  "Isar",
  "Isar",
  "Isar ",
  "Isar mit Flutmulde",
  "Isen",
  "Isen",
  "Isenflutkanal",
  "Itz",
  "Itz",
  "Itz",
  "Jachen",
  "Jenbach",
  "Kahl",
  "Kahl",
  "Kalkgraben",
  "Kaltenbach",
  "Kammel",
  "Kanker",
  "Kanker",
  "Katzbach",
  "Kellersbach",
  "Kieferbach",
  "Kienbach",
  "Kirnach",
  "Kleine Laber",
  "Kleine Ohe",
  "Kleine Sur",
  "Kleine Vils",
  "Kleiner Regen",
  "Kleiner Regen",
  "Kollbach",
  "Kollbach",
  "Kollbach",
  "Konstanzer Ach",
  "Konstanzer Ach",
  "Koserbach",
  "Kreck",
  "Kremnitz",
  "Kronach",
  "Kronach",
  "Krumbach",
  "Krumbach",
  "Königsseer Ache",
  "Kössein",
  "Lamitz",
  "Langenaubach",
  "Lauer",
  "Lauer",
  "Lauter",
  "Lauterach",
  "Lauterbach",
  "Lauterbach",
  "Lech",
  "Lech",
  "Lech",
  "Lech",
  "Lech",
  "Lech",
  "Lehstenbach",
  "Leinleiterbach",
  "Leitzach",
  "Leitzach",
  "Leubas",
  "Leutasch",
  "Lobach",
  "Lochbach",
  "Lohr",
  "Lohr",
  "Loisach",
  "Loisach",
  "Loisach",
  "Loisach",
  "Loisach",
  "Loisach",
  "Loisach",
  "Loisach-Isar-Kanal",
  "Lothdorfer Bach",
  "Lüßbach",
  "Main",
  "Main",
  "Main",
  "Main",
  "Main",
  "Main",
  "Main",
  "Main",
  "Main",
  "Main",
  "Main",
  "Maisach",
  "Mangfall",
  "Mangfall",
  "Mangfall",
  "Mangfall",
  "Mangfall",
  "Markungsgraben",
  "Memminger Ach",
  "Mertseebach",
  "Mertseebach",
  "Merzbach",
  "Metzenbach",
  "Milz",
  "Mindel",
  "Mindel",
  "Mindel",
  "Mindel",
  "Mitternacher Ohe",
  "Mittlere Aurach",
  "Moosach",
  "Mud",
  "Murach",
  "Murach",
  "Murn",
  "Mähringsbach",
  "Mühlbach",
  "Mühlbach",
  "Mühlbach",
  "Mühlberger Ach",
  "Naab",
  "Naab",
  "Naab",
  "Nassach",
  "Neidernach",
  "Nordhalbener Ködel",
  "Nurner Ködel",
  "Obere Argen",
  "Oberreitnauer Ach",
  "Oberteisendorfer Ache",
  "Osterbach",
  "Ostrach",
  "Otterbach",
  "Otterbach",
  "Oybach",
  "Paar",
  "Paar",
  "Paar",
  "Paar",
  "Paar",
  "Partnach",
  "Partnach",
  "Pegnitz",
  "Pegnitz",
  "Pegnitz",
  "Pegnitz",
  "Pegnitz",
  "Pfatter",
  "Pfettrach",
  "Pfreimd",
  "Pfreimd",
  "Pfreimd",
  "Pfreimd",
  "Pfreimd",
  "Pleichach",
  "Prien",
  "Prien",
  "Püttlach",
  "Ramsauer Ache",
  "Ranna",
  "Rauhe Ebrach",
  "Rauhe Ebrach",
  "Rednitz",
  "Rednitz",
  "Rednitz",
  "Regen",
  "Regen",
  "Regen",
  "Regnitz",
  "Regnitz",
  "Reiche Ebrach",
  "Reißingerbach",
  "Reschwasser",
  "Rißbach",
  "Rodach",
  "Rodach",
  "Rodach",
  "Rodach",
  "Rodach",
  "Rohrach",
  "Rosenbach",
  "Rote Traun",
  "Roter Main",
  "Roter Main",
  "Roter Main",
  "Roter Main",
  "Roth",
  "Roth",
  "Rothgraben",
  "Rothsee",
  "Rott",
  "Rott",
  "Rott",
  "Rott",
  "Rott",
  "Rott",
  "Rottach",
  "Rottach",
  "Rottach",
  "Röden",
  "Röslau",
  "Röslau",
  "Röthenbach",
  "Saalach",
  "Saalach",
  "Sachenbach",
  "Sagenbach",
  "Salzach",
  "Salzach",
  "Salzach",
  "Sandrach",
  "Saubach",
  "Sausswasser",
  "Schambach",
  "Scheine",
  "Schinderbach",
  "Schleifermoosach",
  "Schlierach",
  "Schmalnohebach",
  "Schmutter",
  "Schmutter",
  "Schmutter",
  "Schnaittach",
  "Schondra",
  "Schorgast",
  "Schorgast",
  "Schorgast",
  "Schronbach",
  "Schwabach",
  "Schwabach",
  "Schwabach",
  "Schwabinger Bach",
  "Schwarzach",
  "Schwarzach",
  "Schwarzach",
  "Schwarzach",
  "Schwarzach",
  "Schwarzach",
  "Schwarzach",
  "Schwarzach",
  "Schwarzach",
  "Schwarze Laber",
  "Schwarze Laber",
  "Schwarzer Regen",
  "Schwarzer Regen",
  "Schwarzer Regen",
  "Schwarzlofer",
  "Schweinnaab",
  "Schweinnaab",
  "Schwesnitz",
  "Schwäbische Rezat",
  "Schwäbische Rezat",
  "Schwäbische Rezat",
  "Selbitz",
  "Sempt",
  "Sempt",
  "Simbach",
  "Sims",
  "Singold",
  "Singold Hochwasserlauf",
  "Sinn",
  "Sinn",
  "Sinn",
  "Starzlach",
  "Steinach",
  "Steinach",
  "Steinacher Achen",
  "Steinbach",
  "Steinbach",
  "Stillach",
  "Stillach",
  "Stoißer Ache",
  "Streu",
  "Streu",
  "Strogen",
  "Sulz",
  "Sulzach",
  "Sulzbach",
  "Sulzbach",
  "Sur",
  "Sur",
  "Sur",
  "Sylvensteinsee",
  "Sylvensteinsee",
  "Sächsische Saale",
  "Sächsische Saale",
  "Sächsische Saale",
  "Söllbach",
  "Südliche Regnitz",
  "Südliche Regnitz",
  "Tauber",
  "Teisnach",
  "Thulba",
  "Tiefenbach",
  "Tiroler Achen",
  "Tirschenreuther Waldnaab",
  "Tirschenreuther Waldnaab",
  "Tirschenreuther Waldnaab",
  "Trailbach",
  "Trauchgauer Ach",
  "Traufbach",
  "Traun",
  "Traun",
  "Trebgast",
  "Trettach",
  "Triftbach",
  "Trubach",
  "Truppach",
  "Tschirner Ködel",
  "Unterbürger Laber",
  "Untere Argen",
  "Untere Steinach",
  "Untere Steinach",
  "Ussel",
  "Verlorener Bach",
  "Vils",
  "Vils",
  "Vils",
  "Vils",
  "Vils",
  "Vils",
  "Vils",
  "Vils",
  "Vils",
  "Volkach",
  "Volkach",
  "Walchen",
  "Waldbach",
  "Waldnaab",
  "Waldnaab",
  "Warme Pastritz",
  "Warme Steinach",
  "Weilach",
  "Weisach",
  "Weismain",
  "Weißach",
  "Weißach",
  "Weißbach",
  "Weiße Ache",
  "Weiße Traun",
  "Weiße Traun",
  "Weißer Main",
  "Weißer Main",
  "Weißer Regen",
  "Weißer Regen",
  "Wern",
  "Wern",
  "Wern",
  "Wertach",
  "Wertach",
  "Wertach",
  "Wertach",
  "Wertach",
  "Wertach",
  "Wertach",
  "Wertacher Starzlach",
  "Wiesent",
  "Wiesent",
  "Wiesent",
  "Wieseth",
  "Wilde Rodach",
  "Wilde Rodach",
  "Windach",
  "Windach",
  "Windach",
  "Windach",
  "Wolfach",
  "Wolfsteiner Ohe",
  "Wolnzach",
  "Wondreb",
  "Wondreb",
  "Wurmbach",
  "Wörnitz",
  "Wörnitz",
  "Wörnitz",
  "Wörnitz",
  "Würm",
  "Würm",
  "Zeiselbach",
  "Zeller Bach",
  "Zenn",
  "Zenn",
  "Zenn",
  "Zottbach",
  "Zusam",
  "Zusam",
  "Ödbach",
  "Ölschnitz",
  "Ölschnitz",
  "Ölsnitz",
  "Ölsnitz",
  "Östliche",
  "Überseer"
)

# The 6 River with the most stations (corresponds to rivers with at least 9 stations)
considered = sort(table(unlist(lapply(rivers, trimws))), decreasing = T) |> head(n = 6)
considered
save(considered, file = "../data/output/presentation/considered_rivers.Rdata")

# Focus on these 6 for our analysis
# Sometimes, not all stations allow to download the data. Thus, I did not end up exactly with these number of stations



